sonar.projectKey=lab11_joke_game
sonar.projectName=lab11_joke_game
sonar.projectVersion=1.0.0
sonar.projectDescription=FullStack project for Lab 11
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.sonar.json
